### ISSUE TITLE
Till when can it be free service?

### ISSUE THREAD

**Issue by xerosanyam** [CodeKJ/DISIFY#1]
Hi. I love what you've built. I would love to know the stack that you've used to build it.
Also, do you suggest its usage on a production app

**Comment by citronkaste** [comment]
> Hi. I love what you've built. I would love to know the stack that you've used to build it.
> Also, do you suggest its usage on a production app

Hi.

My apologies for late response, just got back from vacation.

Project is running on FuelPHP. Currently its pretty small and lightweight API, but I plan to keep updating and expanding it with new features, like user accounts, private statistics etc.

You can use it in production. I use it myself on pretty big projects. However, I recommend to implement it in some fail-safe manner, so it doesn't break your production environment in case of unexpected response.
