### ISSUE TITLE
How to tell whether services like https://temp-mail.org/ are disposable

### ISSUE THREAD

**Issue by tomBP** [CodeKJ/DISIFY#11]
Hi, 

I'm using your public domain and MX blacklists (thanks by the way) to check for disposable email. 

I'm having a problem with services like https://temp-mail.org/ because they change their MX records regularly. I see that your API correctly catches them but given that they aren't in your public domain and MX lists I don't understand how?  

Any help much appreciated.

**Comment by citronkaste** [comment]
Check if their MX record IP stays the same. They might change MX hostname, that's why we also include hostname IPs in MX blacklist.

**Comment by tomBP** [comment]
Should have thought of that! Thanks! :)
