### ISSUE TITLE
Very nice Projekt

### ISSUE THREAD

**Issue by Martin-Hausleitner** [CodeKJ/DISIFY#12]
I must say nice idea!

Some Ideas for you;

A Scammer Email list
A Spam Email list

**Comment by citronkaste** [comment]
Thanks.

There will be new features coming soon. Including additions to existing email check, new API endpoint to check malicious IP and location. Possibility to register, get your API key (optional) with additional features, statistics. And maybe some validations will be added specifically for spam emails.
