### ISSUE TITLE
Last Domain / MX blacklists update

### ISSUE THREAD

**Issue by blackarcanis** [CodeKJ/DISIFY#14]
Hi !
Could be great to have an updated date for these lists. Just to know if still updated and what is last entries.
Also, I read somewhere you have created a personal space with API Key where we can get some stats. Is it true and where we can found it ?

Thank you so much for you work !

**Comment by citronkaste** [comment]
Hi.

Update dates and statistics will be available in new version of Disify. Need to finish couple more things to run it live.

**Comment by blackarcanis** [comment]
That's perfect ! Thank you for your prompt response :)
