### ISSUE TITLE
This domain has been already submitted! BUT This is valid email address!

### ISSUE THREAD

**Issue by HashemGo** [CodeKJ/DISIFY#15]
email: 4652f1716e@firemailbox.club
 This is valid email address!
{
  "format": true,
  "domain": "firemailbox.club",
  "disposable": false,
  "dns": true
}
but when SUBMIT NEW EMAIL:
This domain has been already submitted!

**Comment by k0t0fey** [comment]
up!

**Comment by citronkaste** [comment]
Solved.
