### ISSUE TITLE
JSON return parameter "whitelist"

### ISSUE THREAD

**Issue by macmcmeans** [CodeKJ/DISIFY#17]
Please excuse my ignorance.

When I check emails having common domains, such as @gmail.com, @yahoo.com, @mail.com, etc., I see your API returns a "whitelist" parameter. I cannot find any reference to this. What is the purpose of this return parameter?

**Comment by citronkaste** [comment]
Domains which have `"whitelist": true` are simply as it says - whitelisted. It means, this domain is ignored for further validation and is considered valid (non-disposable). When SMTP mailbox validation will be introduced, then this parameter will possibly be removed. 

And yes, these whitelist domains are just for some most popular email providers.

**Comment by macmcmeans** [comment]
Thanks! 👍
