### ISSUE TITLE
temp-mail.org domains

### ISSUE THREAD

**Issue by supriyo-biswas** [CodeKJ/DISIFY#18]
Thanks for maintaining this great project for free :)

Currently, disposable emails from temp-mail.org aren't detected. If you could update the list of domains from https://web1.temp-mail.org/request/domains/format/json and https://api.internal.temp-mail.io/api/v2/domains, that would be great.

**Comment by citronkaste** [comment]
Updated.

**Comment by supriyo-biswas** [comment]
Thanks for the prompt reply.

If I understand correctly, the Disify API will report all current and future temp-mail domains from the above URLs as disposable (in other words, there is an automated update process at your end?)

**Comment by citronkaste** [comment]
There are no automated update process, each disposable email provider has their own architecture and it wouldn't be so simple to automate it for every each of them. 

However, MX records for specific domains are also blacklisted. It means, as long as disposable email provider has same MX record (hostname or IP) then all future emails containing this MX record will be also detected as disposable.
