### ISSUE TITLE
Block Abine disposable domains

### ISSUE THREAD

**Issue by supriyo-biswas** [CodeKJ/DISIFY#19]
I found the following disposable domains being operated by Abine. Please add them to your MX blacklist:
```
smtp7.opayq.com
plato.junkemailfilter.com
mx.junkemailfilter.net
mx.junkemailfilter.org
```

Some of the domains that use these MX records are used by `moremobileprivacy.com`, `nowbuzzoff.com`, `beconfidential.com`, `dontrackme.com`, `opayq.com`.

**Comment by citronkaste** [comment]
Added. Thanks.
