### ISSUE TITLE
Possibility to Catch googlemail.com addresses with dots?

### ISSUE THREAD

**Issue by idumlupinar** [CodeKJ/DISIFY#20]
Hello, thank you for creating & sharing this amazing project. It works way better than paid alternatives IMO. One of the projects we use receives spam attacks. Attackers usually use the googlemail.com domain. The accounts use dots (.) and Disify does not mark them. Any chance for you to mark the googlemail.com domain as well?

**Comment by idumlupinar** [comment]
Hello, any updates regarding my request?

**Comment by citronkaste** [comment]
Hi.

googlemail.com is legit gmail.com alias. However, some of those accounts usually have similar username pattern which are used for temporary mail purposes, and in some cases it can be predictable. In new disify version there will be username score value (higher score, more chances specific email is legit). But we cannot assume that on domain level everyone using googlemail.com is temporary address, its still legit gmail alias.

**Comment by idumlupinar** [comment]
Hi @CodeKJ. Thank you for your prompt response. Any ETA for the new release?
