### ISSUE TITLE
theargyllclub.com returns disposable, but is a real company

### ISSUE THREAD

**Issue by jpchow26** [CodeKJ/DISIFY#3]
Hi,

My company been using disify in production to validate email address. We got a user from theargyllclub.com getting blocked, and disify thinks it's a disposable email address, but we're pretty sure it's not. The domain isn't in your blacklist so I can't submit a request on the site. 

{
  "format": true,
  "domain": "theargyllclub.com",
  "disposable": true,
  "dns": true
}

**Comment by citronkaste** [comment]
Hi,

MX records are blacklisted for this domain. Specifically IP `195.130.217.172`
If you are sure that theargyllclub.com is not disposable, we can add it to our white-list. However, MX records itself will stay blacklisted, there are multiple records online with fraudulent emails used from this provider.

**Comment by jpchow26** [comment]
Yes, theargyllclub.com is not disposable. Thanks. I understand that the provider though may be servicing fraudulent emails. Thanks for the quick reply

**Comment by citronkaste** [comment]
Added to whitelist.
