### ISSUE TITLE
Can't submit domains with MX records only

### ISSUE THREAD

**Issue by prryplatypus** [CodeKJ/DISIFY#5]
Title is self explanatory. I am unable to submit domains for blacklisting because they have no A/AAAA records, and only return MX records instead. For example ``emailtown.club``, a temporary email available at [https://www.mohmal.com/en/inbox](https://www.mohmal.com/en/inbox)

**Comment by citronkaste** [comment]
Added to blacklist both domain and MX records.
Thanks for report. Will patch submit issue in next update.

**Comment by prryplatypus** [comment]
Many thanks for your work, mate!

**Comment by prryplatypus** [comment]
Another one, please: marmaryta.club

Available at https://www.temp-mails.com/

**Comment by citronkaste** [comment]
Its not valid email. No DNS records at all , and API does return it as invalid.
