### ISSUE TITLE
Allowing "gmx.com" domain

### ISSUE THREAD

**Issue by blackarcanis** [CodeKJ/DISIFY#7]
Hi !
Currently the domain "gmx.com" is listed as disposable but should not be I think.
The process to create an email on this mail service is more than normal (requiring a name a password etc...).

Can you take a look to remove this from your "disposable" list ?

Thank you for your work.

**Comment by citronkaste** [comment]
Hi,

Removed from blacklist.

**Comment by blackarcanis** [comment]
Perfect, thank you !
