### ISSUE TITLE
Suggestion: add checks on plus sign in gmail addresses

### ISSUE THREAD

**Issue by Thibstars** [CodeKJ/DISIFY#8]
In gmail, an email address could contain a plus sign like `totallyfakeemail+social@gmail.com`. This would in fact be the same email address as `totallyfakeemail@gmail.com`.

Could we perhaps get a flag for this in the output as well?

**Comment by citronkaste** [comment]
Hi,

You mean response like, plus: true/false ? Or validated output of email without plus extension?

**Comment by Thibstars** [comment]
Yes, something like `alias: true/false` seems suitable.

**Comment by citronkaste** [comment]
Now available:
`alias: true`
