### ISSUE TITLE
"This domain is not in our blacklists!" while disposable = true

### ISSUE THREAD

**Issue by blackarcanis** [CodeKJ/DISIFY#9]
Hi !
Got an issue today of an email getting a disposable = true (with no specific reasons, it's a personal domain of a customer).
But when trying to "request" removal I got a message => "This domain is not in our blacklists!"
Seems it is, because disposable is set to true for it :/

Any idea why ?

**Comment by citronkaste** [comment]
Hi!
Can you provide email domain name?

Removal requests check if domain exists in our internal blacklists. But you can still get disposable true if domain provider IP is listed in our MX blacklist.

**Comment by blackarcanis** [comment]
Sure, 
Take a look to "peermusic.com" domain.

Thank you for your help.

**Comment by citronkaste** [comment]
It should be good now. Checked and removed blacklisted MX record.

**Comment by mderazon** [comment]
Hi, this is a more general issue I think
- In my logs, I am seeing emails being flagged as disposable which I suspect they aren't
- I then go to the disify website https://disify.com/ and run the email address there and it shows as _not disposable_

So it seems like for some email addresses, the first time I check they show up as disposable but the second time I check they are not disposable anymore.

Any idea why that might be ?

**Comment by citronkaste** [comment]
Can you provide response you get from api for such case?

**Comment by mderazon** [comment]
Sorry looks like I was getting timeout (had a threshold of 2 seconds to get response) and I flagged it as validation failed, where it didn't really fail...
There are some false positives, but they are consistent

**Comment by blackarcanis** [comment]
Hi !
Having same issue today with another domain, that is not in your blacklist but marked as disposable.
I think it's happening pretty often but we don't get lot of customers taking time to write us about that...

Issue still not be fixed finally ?

**Comment by citronkaste** [comment]
Hi. Can you provide domain?

I am sure this is caused because target domain MX records are blacklisted, not domain itself. For example, put your domain here https://mxtoolbox.com/ , and check for MX records. Take MX IP and search (CTRL+F) through [MX blacklist](https://disify.com/blacklist/mx).

New disify version will include MX record responses, including which MX records were triggered for blacklist - so it will be easier to identify blacklist triggers.

**Comment by futwick** [comment]
Another domain "strata.solutions" is not on the blacklist, the MX record checks out, yet addresses are being rejected as disposable.

**Comment by citronkaste** [comment]
strata.solutions MX records are:
```
eu-smtp-inbound-1.mimecast.com
eu-smtp-inbound-2.mimecast.com
```

Both are listed in [https://disify.com/blacklist/mx](https://disify.com/blacklist/mx) , so disposable response is valid. 
Logic behind removal requests will change so it doesn't confuse you saying "not on the blacklist".

**Comment by futwick** [comment]
apologies, my mistake 
_(I had checked the MX blacklist for the IP address, not the domains)_
